### ISSUE TITLE
INJECT_MANIFEST_PLUGIN is undefined

### ISSUE THREAD

**Issue by nguyenbatranvan** [tobua/inject-manifest-plugin#1]
When use plugin, `INJECT_MANIFEST_PLUGIN` is `undefined`. Have I misconfigured something? Can you take a moment to look at my repo!!
[This is repo](https://github.com/nguyenbatranvan/rspack-sw)

**Comment by nguyenbatranvan** [comment]
i have a error
<img width="408" alt="image" src="https://github.com/tobua/inject-manifest-plugin/assets/19392455/cbf33b88-c180-487a-893f-bed757a363ad">

**Comment by tobua** [comment]
@nguyenbatranvan I see two setups in you project, one for Rsbuild and one for Rspack. I was able to get the Rsbuild part to work when adding `output: { filenameHash: false }` to the configuration. When caching with a service worker, you don't need any hashes. I'm planning to document the Rsbuild setup like this once I've resolved all issues or automatically add this in the plugin. Let me know if this works for you?

While the plugin isn't yet added in the Rspack part, I've added it there and it looks like there are some issues with certain configuration values that you've set. I'll make sure to address those cases in the plugin where possible.

**Comment by nguyenbatranvan** [comment]
> @nguyenbatranvan I see two setups in you project, one for Rsbuild and one for Rspack. I was able to get the Rsbuild part to work when adding `output: { filenameHash: false }` to the configuration. When caching with a service worker, you don't need any hashes. I'm planning to document the Rsbuild setup like this once I've resolved all issues or automatically add this in the plugin. Let me know if this works for you?
> 
> While the plugin isn't yet added in the Rspack part, I've added it there and it looks like there are some issues with certain configuration values that you've set. I'll make sure to address those cases in the plugin where possible.

even if i add that in, it still doesn't work!! I configured `rspack` and `rsbuild`, but I only run `rsbuild`. Here is the `service-worker.js` file after I built it:
![image](https://github.com/tobua/inject-manifest-plugin/assets/19392455/87acd205-8b53-4295-bafa-49c4a8db6815)

**Comment by tobua** [comment]
Hmm, it's working for me, try also updating your dependencies or use [workbox-rspack-plugin](https://github.com/Clarkkkk/workbox-rspack-plugin) which you seem to have already discovered on X. This plugin is way older and I've created it mainly as there was no working plugin available. For the rspack part I've found that the option `filename: 'js/[id].js',` will cause an empty file, maybe you've added that for Rsbuild as well.

**Comment by nguyenbatranvan** [comment]
> Hmm, it's working for me, try also updating your dependencies or use [workbox-rspack-plugin](https://github.com/Clarkkkk/workbox-rspack-plugin) which you seem to have already discovered on X. This plugin is way older and I've created it mainly as there was no working plugin available. For the rspack part I've found that the option `filename: 'js/[id].js',` will cause an empty file, maybe you've added that for Rsbuild as well.

tks so much!!! i will use new plugin
